# Generated by Django 4.2.7 on 2025-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_budget_project_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='project_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
